<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="AngleSharp" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\NetSpider.Core\NetSpider.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Data\**\*" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="NetSpider.Tests.Unit" />
  </ItemGroup>
</Project>
